//Given array arr[] of N positive elements
//The task is to find the Maximum AND Value generated by any pair of the element from the array.
#include <iostream>
#include <cmath>
using namespace std;

#define MAX_ARRAY_VALUE 10000

int count_occurences(int pattern, int arr[], int n)
{
    int count_= 0;
    for (int i = 0; i < n; ++i)
    {
        if ((arr[i] & pattern) == pattern)  ++count_;
    }
    return count_;
}

int and_max(int arr[], int n)
{
    int res = 0, ct;
    for (int bit = log2(MAX_ARRAY_VALUE)+1; bit >= 0; --bit)
    {
        ct = count_occurences(res | (1 << bit), arr, n);
        if (ct >= 2)    res |= (1 << bit);
    }
    return res;
}

int main()
{
    cout << "Program to find maximum AND value of two elements in an array" << endl;
    int n;
    cout << "Array Size: "; cin >> n;
    cout << "Enter array elements separated by space" << endl;
    int arr[n];
    for (int i = 0; i < n; ++i)
        cin >> arr[i];

    cout << "MAX AND VALUE: " << and_max(arr, n);
}
